import { Injectable, signal } from '@angular/core';
import type { GameCardView } from '@munchkin-lan/contracts';
import type { UserFacingError } from './lobby-client';

export type AppLocale = 'ru' | 'en';

const ENGLISH = {
  language: 'Language',
  russian: 'Russian',
  english: 'English',
  enterFullscreen: 'Enter fullscreen',
  exitFullscreen: 'Exit fullscreen',
  brandTagline: 'LAN card adventure',
  online: 'Online',
  reconnecting: 'Reconnecting',
  turn: 'Turn',
  victory: 'Victory!',
  winnerMessage: 'reached the winning level and won the game.',
  rematch: 'Play again',
  returnToLobby: 'Return to lobby',
  waitingForHostAfterGame: 'Waiting for the host to choose what happens next…',
  deckSizes: 'Deck sizes',
  door: 'Door',
  treasure: 'Treasure',
  players: 'Players',
  currentTurn: 'Current turn',
  gameTable: 'Game table',
  monsterEncounter: 'Monster encounter',
  level: 'Level',
  combatPower: 'Power',
  equipmentBonus: 'Equipment bonus',
  yourPower: 'Your power',
  monsterPower: 'Monster power',
  combatRewards: 'Rewards',
  badStuff: 'Bad stuff on a failed escape',
  badStuffLoseLevel: 'Lose levels:',
  badStuffDiscardHand: 'Discard random cards from hand:',
  badStuffDiscardEquipment: 'Discard random equipped items:',
  badStuffChooseHand: 'Choose cards to discard from hand:',
  badStuffChooseEquipment: 'Choose equipped items to discard:',
  badStuffDiscardRole: 'Discard role:',
  badStuffDeath: 'Death: discard cards, equipment, class and race',
  runAwaySucceeded: 'Escape succeeded',
  runAwayFailed: 'Escape failed',
  runAwayResults: 'Escape attempts',
  dieRoll: 'Die roll',
  badStuffApplied: 'The monster’s bad stuff was applied.',
  levels: 'levels',
  treasures: 'treasures',
  temporaryBonus: 'Temporary bonus',
  monsterBonus: 'Monster bonus',
  helperContribution: 'Helper contribution',
  requestHelp: 'Ask for help',
  helpRequested: 'Help requested from',
  helperJoined: 'Helper joined',
  combatHistory: 'Combat history',
  gameHistory: 'Game history',
  gameHistoryDescription: 'Complete server-confirmed history of this game.',
  closeGameHistory: 'Close game history',
  emptyGameHistory: 'No game actions have been recorded yet.',
  historyEntryMeta: 'Turn',
  historyUnknownPlayer: 'Unknown player',
  historyUnknownCard: 'unknown card',
  logPlayerAdded: 'joined the game.',
  logGameStarted: 'The game started. First turn:',
  logCardsDealt: 'Your starting cards were dealt',
  logTurnStarted: 'Turn started for',
  logTurnEnded: 'ended the turn.',
  logDoorKicked: 'kicked the door and revealed',
  logDeckReshuffled: 'discard was shuffled back into the deck.',
  logLookedForTrouble: 'looked for trouble and played',
  logCardDrawn: 'You drew',
  logCardAdded: 'put the revealed card into their hand:',
  logCardsDiscarded: 'discarded:',
  logCardsDiscardedSummary: 'discarded cards:',
  logCardDiscardRequired: 'must choose cards to discard:',
  logCurseResolved: 'Curse resolved:',
  logOnPlayer: 'on',
  logCombatUpdated: 'Combat power changed to',
  logCombatVictoryDeclared: 'claimed victory; reactions are now required.',
  logCombatReactionPassed: 'will not intervene.',
  logCombatReactionsReset: 'Combat changed; previous reaction confirmations were reset.',
  logCombatVictoryCancelled:
    'The victory claim was cancelled because the adventurers lost the lead.',
  logCombatWon: 'defeated',
  logMonsterAdded: 'added a Monster to combat:',
  logMonsterCloned: 'cloned a Monster in combat:',
  logRunAway: 'rolled to escape from',
  logBadStuff: 'Bad stuff applied from',
  logLevelGained: 'gained levels:',
  logLevelLost: 'lost levels:',
  logTreasureGained: 'gained Treasure cards:',
  logRoomLooted: 'looted the room.',
  logCardPlayed: 'played',
  logForPlayers: 'for the adventurers',
  logForMonster: 'for the monster',
  logItemEquipped: 'equipped',
  logItemUnequipped: 'unequipped',
  logRolePlayed: 'played a role:',
  logItemsSold: 'sold:',
  logItemTraded: 'gave',
  logToPlayer: 'to',
  logCharityGiven: 'gave charity cards:',
  logCharityDiscarded: 'discarded charity cards:',
  logCharityCardsGiven: 'gave these charity cards:',
  logCharityCardsDiscarded: 'discarded these charity cards:',
  logPlayerDied: 'died.',
  logPlayerRevived: 'returned to the adventure.',
  logGameFinished: 'won the game at level',
  historyCombatStarted: 'started combat with',
  historyMonsterAdded: 'added to combat',
  historyMonsterCloned: 'created a clone of',
  historyHelpRequested: 'asked for help from',
  historyHelpAccepted: 'joined the combat with',
  historyPlayedForPlayers: 'played for the adventurers',
  historyPlayedForMonster: 'played for the monster',
  historyPlayedCombatCurse: 'played a combat Curse on',
  playForPlayers: 'Play for adventurers',
  playForMonster: 'Play for monster',
  addMonsterToCombat: 'Add a Monster from hand',
  playCombatCurse: 'Play combat Curse',
  yourMove: 'Your move',
  chooseAction: 'Choose an available action below.',
  anotherPlayerActs: 'Another adventurer is acting',
  handPrivate: 'Your hand remains private.',
  yourAdventurer: 'Your adventurer',
  equipment: 'Equipment',
  nothingEquipped: 'Nothing equipped yet',
  equip: 'Equip',
  unequip: 'Unequip',
  roles: 'Class and race',
  none: 'None',
  dead: 'Dead — new cards arrive at the start of your next turn',
  value: 'Value',
  playRole: 'Use role',
  curseTo: 'Curse',
  sell: 'Sell for a level',
  tradeTo: 'Give to',
  charity: 'Charity',
  charityTitle: 'Resolve charity',
  charityDescription: 'Choose exactly the excess cards to remove from your hand.',
  closeCharity: 'Close charity',
  charityRecipient: 'Recipient among the lowest-level players',
  charityDiscardHint:
    'Because you are among the lowest-level players, these cards will be discarded.',
  randomCharity: 'Choose randomly',
  confirmCharity: 'Confirm charity',
  recentEvents: 'Latest actions',
  publicEvents: 'Cards on the table',
  publicEventsHint: 'New public card events appear here without blocking play.',
  openEventDetails: 'Open event details',
  dismissEvent: 'Dismiss event',
  eventDetails: 'Event details',
  eventNumber: 'Event',
  source: 'Source',
  target: 'Target',
  relatedCards: 'Related cards',
  cardEffects: 'Effects',
  equipmentSlot: 'Slot',
  openCardDetails: 'Open card details',
  cardOpenDetails: 'Tap to read the card',
  cardPlayableNow: 'Available now; tap to read before acting',
  playableNow: 'Available now',
  cardReasonFinished: 'The game is already finished.',
  cardReasonPendingDecision: 'Resolve the pending decision first.',
  cardReasonReactionWindow: 'Only combat reactions are allowed while victory is pending.',
  cardReasonReactionConfirmed: 'You already passed and cannot intervene until combat changes.',
  cardReasonWaitingTurn: 'This can only be used during your turn.',
  cardReasonCombatActive: 'Equipment and roles cannot be changed during combat.',
  cardReasonNoCombat: 'This card requires an active combat.',
  cardReasonWrongPhase: 'This card cannot be used in the current phase.',
  cardReasonNoAction: 'This card has no available action right now.',
  expectedDiscard: 'Waiting for a card choice from',
  expectedHelpResponse: 'Waiting for a help response from',
  expectedCombatDecision: 'Waiting for a combat decision from',
  expectedCombatReactions: 'Waiting for reactions from',
  expectedTurnAction: 'Waiting for an action from',
  statusDiscardingCards: 'is choosing cards to discard…',
  statusRespondingToHelp: 'is responding to a help request…',
  statusResolvingCombat: 'is deciding the combat outcome…',
  statusCombatReactionConfirmed: 'You will not intervene. Waiting for the other players…',
  statusCombatReactionNeeded: 'Choose a reaction or confirm that you will not intervene.',
  statusWaitingInLobby: 'is waiting in the lobby…',
  statusStartingTurn: 'is starting the turn…',
  statusOpeningDoor: 'is opening the door…',
  statusResolvingDoor: 'is resolving the Door card…',
  statusChoosingNextAction: 'is choosing what to do next…',
  statusLootingRoom: 'is looting the room…',
  statusEndingTurn: 'is ending the turn…',
  playerSide: 'Adventurers',
  monsterSide: 'Monster',
  combatTotals: 'Combat totals',
  versus: 'vs',
  total: 'Total',
  monsterBase: 'Monster base power',
  monsterModifiers: 'Monster modifiers',
  victoryReactionWindow: 'Victory reaction',
  victoryClaimPending: 'Victory has been claimed. Every other player must respond.',
  reactionConfirmedPlayers: 'Confirmed',
  reactionWaitingPlayers: 'Still waiting',
  reactionAlreadyConfirmed:
    'You confirmed that you will not intervene. Combat cards are locked until combat changes.',
  availableReactions: 'Available reaction cards',
  noReactionCards: 'No reaction cards in your hand. You can still choose “I won’t intervene”.',
  clone: 'Clone',
  chooseMonsterTarget: 'Choose a Monster target',
  chooseTarget: 'Choose a target',
  validTargetsHighlighted: 'Only highlighted players can be selected.',
  selectTarget: 'Select target',
  cancel: 'Cancel',
  confirm: 'Confirm',
  confirmAction: 'Confirm action',
  chooseCurseTarget: 'Choose curse target',
  chooseTradeTarget: 'Choose recipient',
  openCharacter: 'Open character',
  character: 'Character',
  closeCharacter: 'Close character',
  cardsInHand: 'Cards in hand',
  deadShort: 'Dead',
  alive: 'Alive',
  connected: 'Connected',
  activePlayer: 'Active player',
  inCombat: 'In current combat',
  informationOnly: 'Another player’s character is informational only. Their hand remains private.',
  slotLeftHand: 'Left hand',
  slotRightHand: 'Right hand',
  emptySlot: 'Empty',
  twoHanded: 'Two-handed',
  effectCombatBonus: 'Combat bonus',
  effectMonsterBonus: 'Monster combat bonus',
  effectMonsterStrength: 'Monster strength',
  effectAddMonster: 'Add a selected hand Monster to the current combat',
  effectCloneMonster: 'Clone a selected Monster with its current modifiers',
  effectGainLevel: 'Gain levels',
  effectLoseLevel: 'Lose levels',
  effectDrawCards: 'Draw cards',
  effectDiscardRandom: 'Discard random cards',
  effectDiscardChosen: 'Choose cards to discard',
  effectDiscardRole: 'Discard role',
  effectDeath: 'Death',
  cardLevelReward: 'Level reward',
  cardTreasureReward: 'Treasures',
  cardCurrentLevel: 'Current level',
  cardBadStuff: 'Bad stuff',
  cardHands: 'Hands used',
  cardPrice: 'Price',
  cardRestrictions: 'Restrictions',
  cardNoRestrictions: 'none',
  cardClassRestriction: 'Class',
  cardRaceRestriction: 'Race',
  cardTiming: 'Timing',
  cardTarget: 'Target',
  timingTurn: 'during your turn',
  timingActiveCombat: 'during combat',
  timingVictoryReaction: 'during the victory reaction',
  timingWhenDrawn: 'when drawn',
  targetSelf: 'self',
  targetAnyPlayer: 'any player',
  targetCombatPlayers: 'active adventurer or helper',
  targetCombatPlayer: 'one combat participant',
  targetMonsterEncounter: 'one Monster encounter',
  targetHandMonster: 'a Monster from your hand',
  decisionRequired: 'Decision required',
  chooseCardsToDiscard: 'Choose exactly this many cards to discard',
  playerChoosingCards: 'is choosing cards to discard…',
  selectedCards: 'Selected',
  confirmDiscard: 'Discard selected cards',
  sellItems: 'Sell items',
  saleDescription: 'Select one or more items worth at least 1,000 total.',
  closeSale: 'Close item sale',
  saleTotal: 'Total value',
  saleLevels: 'Levels received',
  saleRemainder: 'Unused remainder',
  confirmSale: 'Sell selected items',
  lookForTroubleDescription: 'Choose exactly one Monster from your hand to start a normal combat.',
  closeLookForTrouble: 'Close monster selection',
  confirmLookForTrouble: 'Fight the selected monster',
  slotHead: 'Head',
  slotBody: 'Body',
  slotFeet: 'Feet',
  slotHands: 'Hands',
  yourHand: 'Your hand',
  closeCardDetails: 'Close card details',
  availableActions: 'Available actions',
  combatInProgress: 'Combat in progress',
  waitingForTurn: 'Waiting for your turn…',
  roomCode: 'Room code',
  shareRoom: 'Share the code with friends on this Wi-Fi. Sessions recover after refresh.',
  offline: 'Offline',
  you: 'You',
  host: 'Host',
  starting: 'Starting…',
  startGame: 'Start game',
  singlePlayerNote: 'Development mode allows a one-player game.',
  waitingForHost: 'Waiting for the host to start…',
  gatherParty: 'Gather your party',
  welcomeTitle: 'Adventure is better together.',
  welcomeCopy: 'Create a room or join friends already playing on your local network.',
  yourName: 'Your name',
  createRoom: 'Create room',
  orJoinRoom: 'or join a room',
  joinRoom: 'Join room',
  phaseLobby: 'Waiting in lobby',
  phaseTurnStart: 'Kick down the door',
  phaseKickDoor: 'Opening the door',
  phaseDoorResolution: 'Resolving the door',
  phasePostDoor: 'Choose what to do next',
  phaseLootRoom: 'Looting the room',
  phaseEndTurn: 'End the turn',
  phaseFinished: 'Game finished',
  actionKickDoor: 'Kick the door',
  actionLookForTrouble: 'Look for trouble',
  actionAcceptHelp: 'Accept help request',
  actionDeclareCombatVictory: 'Claim victory',
  actionPassCombatReaction: 'I won’t intervene',
  actionRunAway: 'Run away',
  actionLootRoom: 'Loot the room',
  actionEndTurn: 'End turn',
  cardMonster: 'Monster',
  cardCurse: 'Curse',
  cardCombatCurse: 'Combat Curse',
  cardEquipment: 'Equipment',
  cardTemporaryBonus: 'Temporary bonus',
  cardMonsterModifier: 'Monster modifier',
  cardAddMonster: 'Add Monster',
  cardCloneMonster: 'Clone Monster',
  cardOther: 'Other',
  cardClass: 'Class',
  cardRace: 'Race',
  errorConnectionLost: 'Connection lost. Reconnecting…',
  errorServerUnavailable: 'Cannot reach the game server. Retrying…',
  errorAlreadyInRoom: 'This connection is already in a room.',
  errorGameStarted: 'The game has already started.',
  errorInvalidPlayerName: 'Enter a player name.',
  errorInvalidRoomCode: 'Enter a valid 4-character room code.',
  errorInvalidSession: 'The saved session is invalid or has expired.',
  errorNotHost: 'Only the host can start the game.',
  errorPlayerNotFound: 'This player was not found in the room.',
  errorRoomFull: 'The room is full (maximum 6 players).',
  errorRoomNotFound: 'No room exists with that code.',
  errorGameNotFinished: 'The game has not finished yet.',
  errorGameNotFound: 'The game is not running.',
  errorNotActivePlayer: 'It is not your turn.',
  errorInvalidPhase: 'This action is not available right now.',
  errorNotEnoughPlayers: 'There are not enough players to start.',
  errorActorNotFound: 'This player is not part of the game.',
  errorCardNotInHand: 'That card is not in your hand.',
  errorCardNotEquipped: 'That item is not equipped.',
  errorCardNotEquipment: 'That card is not equipment.',
  errorCardNotPlayable: 'That card cannot be played in this combat.',
  errorInvalidTarget: 'That card has no valid target.',
  errorInvalidHelper: 'That player cannot help in this combat.',
  errorHelpAlreadyAccepted: 'A helper has already joined this combat.',
  errorHelpNotRequested: 'You do not have an active help request.',
  errorCombatNotWon: 'Your power must be greater than the monster power.',
  errorReactionWindowActive: 'Only reactions are allowed while the victory claim is pending.',
  errorReactionAlreadyConfirmed: 'You already chose not to intervene in this reaction round.',
  errorStaleCombatState: 'Combat changed. Review the current powers and claim victory again.',
  errorStaleCombatReaction: 'That reaction round is no longer current. Review the updated combat.',
  errorEquipmentSlotOccupied: 'That equipment slot is already occupied.',
  errorNotEnoughFreeHands: 'You do not have enough free hands.',
  errorClassRequired: 'This item requires a different Class.',
  errorRaceRequired: 'This item requires a different Race.',
  errorInvalidRecipient: 'Choose a valid recipient.',
  errorInvalidCardSelection: 'Choose the required cards.',
  errorInsufficientSaleValue: 'The selected items are not worth 1,000 gold.',
  errorHandLimitExceeded: 'Resolve charity before ending the turn.',
  errorCommandNotAvailable: 'This action is not available yet.',
  errorDeckEmpty: 'There are no cards left in that deck.',
  errorDuplicatePlayer: 'That player is already in the game.',
  errorInsufficientCards: 'The deck and discard do not contain enough cards for this action.',
  errorPlayerLimit: 'The game already has the maximum number of players.',
  errorUnknown: 'Something went wrong. Please try again.',
} as const;

type TranslationKey = keyof typeof ENGLISH;

const RUSSIAN: Record<TranslationKey, string> = {
  language: 'Язык',
  russian: 'Русский',
  english: 'English',
  enterFullscreen: 'На весь экран',
  exitFullscreen: 'Выйти из полноэкранного режима',
  brandTagline: 'Карточное приключение по локальной сети',
  online: 'В сети',
  reconnecting: 'Переподключение',
  turn: 'Ход',
  victory: 'Победа!',
  winnerMessage: 'достиг победного уровня и выиграл партию.',
  rematch: 'Сыграть ещё раз',
  returnToLobby: 'Вернуться в лобби',
  waitingForHostAfterGame: 'Ждём, когда ведущий выберет, что делать дальше…',
  deckSizes: 'Размеры колод',
  door: 'Двери',
  treasure: 'Сокровища',
  players: 'Игроки',
  currentTurn: 'Сейчас ходит',
  gameTable: 'Игровой стол',
  monsterEncounter: 'Встреча с монстром',
  level: 'Уровень',
  combatPower: 'Сила',
  equipmentBonus: 'Бонус снаряжения',
  yourPower: 'Ваша сила',
  monsterPower: 'Сила монстра',
  combatRewards: 'Награда',
  badStuff: 'Непотребство при неудачном побеге',
  badStuffLoseLevel: 'Потерять уровни:',
  badStuffDiscardHand: 'Сбросить случайные карты с руки:',
  badStuffDiscardEquipment: 'Сбросить случайные надетые предметы:',
  badStuffChooseHand: 'Выбрать карты для сброса с руки:',
  badStuffChooseEquipment: 'Выбрать надетые предметы для сброса:',
  badStuffDiscardRole: 'Сбросить роль:',
  badStuffDeath: 'Смерть: сбросить карты, снаряжение, класс и расу',
  runAwaySucceeded: 'Побег удался',
  runAwayFailed: 'Побег не удался',
  runAwayResults: 'Попытки побега',
  dieRoll: 'Бросок кубика',
  badStuffApplied: 'Непотребство монстра применено.',
  levels: 'ур.',
  treasures: 'сокровищ',
  temporaryBonus: 'Временный бонус',
  monsterBonus: 'Бонус монстра',
  helperContribution: 'Вклад помощника',
  requestHelp: 'Позвать на помощь',
  helpRequested: 'Помощь запрошена у',
  helperJoined: 'Помощник в бою',
  combatHistory: 'История боя',
  gameHistory: 'История игры',
  gameHistoryDescription: 'Полная история подтверждённых сервером событий этой партии.',
  closeGameHistory: 'Закрыть историю игры',
  emptyGameHistory: 'В игре пока не записано ни одного действия.',
  historyEntryMeta: 'Ход',
  historyUnknownPlayer: 'Неизвестный игрок',
  historyUnknownCard: 'неизвестная карта',
  logPlayerAdded: 'присоединился к игре.',
  logGameStarted: 'Игра началась. Первый ход:',
  logCardsDealt: 'Вам раздали начальные карты',
  logTurnStarted: 'Ход начался у игрока',
  logTurnEnded: 'завершил ход.',
  logDoorKicked: 'вышиб дверь и открыл карту',
  logDeckReshuffled: 'сброс перемешан и возвращён в колоду.',
  logLookedForTrouble: 'сам нашёл неприятности и сыграл монстра',
  logCardDrawn: 'Вы получили карту',
  logCardAdded: 'забрал открытую карту в руку:',
  logCardsDiscarded: 'сбросил карты:',
  logCardsDiscardedSummary: 'сбросил карт:',
  logCardDiscardRequired: 'должен выбрать карты для сброса:',
  logCurseResolved: 'Сработало проклятие',
  logOnPlayer: 'на игрока',
  logCombatUpdated: 'Силы в бою изменились:',
  logCombatVictoryDeclared: 'заявил победу; теперь требуются ответы остальных игроков.',
  logCombatReactionPassed: 'не будет вмешиваться.',
  logCombatReactionsReset: 'Бой изменился; предыдущие подтверждения сброшены.',
  logCombatVictoryCancelled: 'Заявление победы отменено: приключенцы потеряли преимущество.',
  logCombatWon: 'победил монстра',
  logMonsterAdded: 'добавил монстра в бой:',
  logMonsterCloned: 'клонировал монстра в бою:',
  logRunAway: 'бросил кубик для побега от',
  logBadStuff: 'Применено непотребство от',
  logLevelGained: 'получил уровни:',
  logLevelLost: 'потерял уровни:',
  logTreasureGained: 'получил карты сокровищ:',
  logRoomLooted: 'обыскал комнату.',
  logCardPlayed: 'сыграл карту',
  logForPlayers: 'за приключенцев',
  logForMonster: 'за монстра',
  logItemEquipped: 'надел',
  logItemUnequipped: 'снял',
  logRolePlayed: 'сыграл роль:',
  logItemsSold: 'продал:',
  logItemTraded: 'передал',
  logToPlayer: 'игроку',
  logCharityGiven: 'передал карт как милостыню:',
  logCharityDiscarded: 'сбросил карт при раздаче милостыни:',
  logCharityCardsGiven: 'передал эти карты как милостыню:',
  logCharityCardsDiscarded: 'сбросил эти карты при раздаче милостыни:',
  logPlayerDied: 'погиб.',
  logPlayerRevived: 'вернулся в приключение.',
  logGameFinished: 'выиграл игру на уровне',
  historyCombatStarted: 'начал бой с',
  historyMonsterAdded: 'добавил в бой',
  historyMonsterCloned: 'создал клона монстра',
  historyHelpRequested: 'попросил помощи у',
  historyHelpAccepted: 'вступил в бой вместе с',
  historyPlayedForPlayers: 'сыграл за приключенцев',
  historyPlayedForMonster: 'сыграл за монстра',
  historyPlayedCombatCurse: 'сыграл боевое проклятие на игрока',
  playForPlayers: 'Сыграть за приключенцев',
  playForMonster: 'Сыграть за монстра',
  addMonsterToCombat: 'Добавить монстра с руки',
  playCombatCurse: 'Сыграть боевое проклятие',
  yourMove: 'Ваш ход',
  chooseAction: 'Выберите доступное действие ниже.',
  anotherPlayerActs: 'Другой приключенец делает ход',
  handPrivate: 'Ваши карты по-прежнему видны только вам.',
  yourAdventurer: 'Ваш приключенец',
  equipment: 'Снаряжение',
  nothingEquipped: 'Пока ничего не надето',
  equip: 'Надеть',
  unequip: 'Снять',
  roles: 'Класс и раса',
  none: 'Нет',
  dead: 'Мёртв — новые карты будут выданы в начале следующего хода',
  value: 'Цена',
  playRole: 'Выбрать роль',
  curseTo: 'Проклясть',
  sell: 'Продать за уровень',
  tradeTo: 'Передать игроку',
  charity: 'Милостыня',
  charityTitle: 'Раздать милостыню',
  charityDescription: 'Выберите точное количество лишних карт из руки.',
  closeCharity: 'Закрыть милостыню',
  charityRecipient: 'Получатель среди игроков минимального уровня',
  charityDiscardHint:
    'Вы среди игроков минимального уровня, поэтому выбранные карты уйдут в сброс.',
  randomCharity: 'Выбрать случайно',
  confirmCharity: 'Подтвердить милостыню',
  recentEvents: 'Последние действия',
  publicEvents: 'Карты на столе',
  publicEventsHint: 'Новые публичные карточные события появляются здесь и не блокируют игру.',
  openEventDetails: 'Открыть подробности события',
  dismissEvent: 'Скрыть событие',
  eventDetails: 'Подробности события',
  eventNumber: 'Событие',
  source: 'Источник',
  target: 'Цель',
  relatedCards: 'Связанные карты',
  cardEffects: 'Эффекты',
  equipmentSlot: 'Слот',
  openCardDetails: 'Открыть описание карты',
  cardOpenDetails: 'Нажмите, чтобы прочитать карту',
  cardPlayableNow: 'Доступна сейчас; нажмите, чтобы прочитать перед действием',
  playableNow: 'Можно сыграть',
  cardReasonFinished: 'Партия уже завершена.',
  cardReasonPendingDecision: 'Сначала завершите ожидающее решение.',
  cardReasonReactionWindow: 'Пока заявлена победа, разрешены только реакции на бой.',
  cardReasonReactionConfirmed:
    'Вы уже отказались вмешиваться и не можете разыгрывать реакции, пока бой не изменится.',
  cardReasonWaitingTurn: 'Эту карту можно использовать только в свой ход.',
  cardReasonCombatActive: 'Во время боя нельзя менять снаряжение и роли.',
  cardReasonNoCombat: 'Для этой карты нужен активный бой.',
  cardReasonWrongPhase: 'Эту карту нельзя использовать в текущей фазе.',
  cardReasonNoAction: 'Сейчас у этой карты нет доступного действия.',
  expectedDiscard: 'Ждём выбора карт от игрока',
  expectedHelpResponse: 'Ждём ответа на помощь от игрока',
  expectedCombatDecision: 'Ждём решения в бою от игрока',
  expectedCombatReactions: 'Ждём реакций от игроков',
  expectedTurnAction: 'Ждём действия от игрока',
  statusDiscardingCards: 'выбирает карты для сброса…',
  statusRespondingToHelp: 'отвечает на просьбу о помощи…',
  statusResolvingCombat: 'решает исход боя…',
  statusCombatReactionConfirmed: 'Вы не вмешиваетесь. Ждём остальных игроков…',
  statusCombatReactionNeeded: 'Сыграйте реакцию или подтвердите, что не вмешиваетесь.',
  statusWaitingInLobby: 'ждёт в комнате…',
  statusStartingTurn: 'начинает ход…',
  statusOpeningDoor: 'открывает дверь…',
  statusResolvingDoor: 'разыгрывает карту Двери…',
  statusChoosingNextAction: 'выбирает следующее действие…',
  statusLootingRoom: 'обыскивает комнату…',
  statusEndingTurn: 'завершает ход…',
  playerSide: 'Приключенцы',
  monsterSide: 'Монстр',
  combatTotals: 'Итоговые силы боя',
  versus: 'против',
  total: 'Итого',
  monsterBase: 'Базовая сила монстра',
  monsterModifiers: 'Модификаторы монстра',
  victoryReactionWindow: 'Окно реакции на победу',
  victoryClaimPending: 'Победа заявлена. Каждый другой игрок должен ответить.',
  reactionConfirmedPlayers: 'Подтвердили',
  reactionWaitingPlayers: 'Ожидаются',
  reactionAlreadyConfirmed:
    'Вы подтвердили, что не вмешиваетесь. Боевые карты заблокированы до изменения боя.',
  availableReactions: 'Доступные карты реакции',
  noReactionCards: 'На руке нет карт реакции. Можно выбрать «Не вмешиваюсь».',
  clone: 'Клон',
  chooseMonsterTarget: 'Выберите конкретного монстра',
  chooseTarget: 'Выберите цель',
  validTargetsHighlighted: 'Можно выбрать только подсвеченных игроков.',
  selectTarget: 'Выбрать цель',
  cancel: 'Отмена',
  confirm: 'Подтвердить',
  confirmAction: 'Подтвердите действие',
  chooseCurseTarget: 'Выбрать цель проклятия',
  chooseTradeTarget: 'Выбрать получателя',
  openCharacter: 'Открыть персонажа',
  character: 'Персонаж',
  closeCharacter: 'Закрыть персонажа',
  cardsInHand: 'Карт в руке',
  deadShort: 'Мёртв',
  alive: 'Жив',
  connected: 'Подключён',
  activePlayer: 'Активный игрок',
  inCombat: 'Участвует в текущем бою',
  informationOnly: 'Окно чужого персонажа только информационное. Его рука остаётся скрытой.',
  slotLeftHand: 'Левая рука',
  slotRightHand: 'Правая рука',
  emptySlot: 'Пусто',
  twoHanded: 'Двуручный предмет',
  effectCombatBonus: 'Бонус в бою',
  effectMonsterBonus: 'Бонус силы монстра',
  effectMonsterStrength: 'Сила монстра',
  effectAddMonster: 'Добавить выбранного монстра с руки в текущий бой',
  effectCloneMonster: 'Клонировать выбранного монстра с текущими модификаторами',
  effectGainLevel: 'Получить уровни',
  effectLoseLevel: 'Потерять уровни',
  effectDrawCards: 'Взять карты',
  effectDiscardRandom: 'Сбросить случайные карты',
  effectDiscardChosen: 'Выбрать карты для сброса',
  effectDiscardRole: 'Сбросить роль',
  effectDeath: 'Смерть',
  cardLevelReward: 'Награда уровнями',
  cardTreasureReward: 'Сокровища',
  cardCurrentLevel: 'Текущий уровень',
  cardBadStuff: 'Непотребство',
  cardHands: 'Занято рук',
  cardPrice: 'Цена',
  cardRestrictions: 'Ограничения',
  cardNoRestrictions: 'нет',
  cardClassRestriction: 'Класс',
  cardRaceRestriction: 'Раса',
  cardTiming: 'Время применения',
  cardTarget: 'Цель',
  timingTurn: 'в свой ход',
  timingActiveCombat: 'во время боя',
  timingVictoryReaction: 'в окне реакции на победу',
  timingWhenDrawn: 'при открытии',
  targetSelf: 'на себя',
  targetAnyPlayer: 'любой игрок',
  targetCombatPlayers: 'активный игрок или помощник',
  targetCombatPlayer: 'один участник боя',
  targetMonsterEncounter: 'один монстр в бою',
  targetHandMonster: 'монстр с вашей руки',
  decisionRequired: 'Требуется решение',
  chooseCardsToDiscard: 'Выберите ровно столько карт для сброса',
  playerChoosingCards: 'выбирает карты для сброса…',
  selectedCards: 'Выбрано',
  confirmDiscard: 'Сбросить выбранные карты',
  sellItems: 'Продать вещи',
  saleDescription: 'Выберите одну или несколько вещей общей стоимостью не менее 1000.',
  closeSale: 'Закрыть продажу вещей',
  saleTotal: 'Общая стоимость',
  saleLevels: 'Получено уровней',
  saleRemainder: 'Сгорит остаток',
  confirmSale: 'Продать выбранные вещи',
  lookForTroubleDescription: 'Выберите ровно одного монстра с руки, чтобы начать обычный бой.',
  closeLookForTrouble: 'Закрыть выбор монстра',
  confirmLookForTrouble: 'Сразиться с выбранным монстром',
  slotHead: 'Голова',
  slotBody: 'Тело',
  slotFeet: 'Ноги',
  slotHands: 'Руки',
  yourHand: 'Ваши карты',
  closeCardDetails: 'Закрыть описание карты',
  availableActions: 'Доступные действия',
  combatInProgress: 'Идёт бой',
  waitingForTurn: 'Ожидание вашего хода…',
  roomCode: 'Код комнаты',
  shareRoom:
    'Сообщите этот код друзьям в той же сети Wi-Fi. После обновления страницы игра восстановится.',
  offline: 'Не в сети',
  you: 'Вы',
  host: 'Ведущий',
  starting: 'Запуск…',
  startGame: 'Начать игру',
  singlePlayerNote: 'В режиме разработки можно играть одному.',
  waitingForHost: 'Ждём, когда ведущий начнёт игру…',
  gatherParty: 'Соберите команду',
  welcomeTitle: 'Вместе приключаться веселее.',
  welcomeCopy:
    'Создайте комнату или присоединитесь к друзьям, которые уже играют в вашей локальной сети.',
  yourName: 'Ваше имя',
  createRoom: 'Создать комнату',
  orJoinRoom: 'или присоединиться',
  joinRoom: 'Войти в комнату',
  phaseLobby: 'Ожидание в комнате',
  phaseTurnStart: 'Вышибите дверь',
  phaseKickDoor: 'Открываем дверь',
  phaseDoorResolution: 'Разбираемся с находкой',
  phasePostDoor: 'Выберите следующее действие',
  phaseLootRoom: 'Обыскиваем комнату',
  phaseEndTurn: 'Завершите ход',
  phaseFinished: 'Игра окончена',
  actionKickDoor: 'Вышибить дверь',
  actionLookForTrouble: 'Искать неприятности',
  actionAcceptHelp: 'Принять просьбу о помощи',
  actionDeclareCombatVictory: 'Заявить победу',
  actionPassCombatReaction: 'Не вмешиваюсь',
  actionRunAway: 'Сбежать',
  actionLootRoom: 'Обыскать комнату',
  actionEndTurn: 'Завершить ход',
  cardMonster: 'Монстр',
  cardCurse: 'Проклятие',
  cardCombatCurse: 'Боевое проклятие',
  cardEquipment: 'Снаряжение',
  cardTemporaryBonus: 'Разовый бонус',
  cardMonsterModifier: 'Усиление монстра',
  cardAddMonster: 'Добавить монстра',
  cardCloneMonster: 'Клонировать монстра',
  cardOther: 'Прочее',
  cardClass: 'Класс',
  cardRace: 'Раса',
  errorConnectionLost: 'Соединение потеряно. Переподключаемся…',
  errorServerUnavailable: 'Не удаётся подключиться к игровому серверу. Повторяем попытку…',
  errorAlreadyInRoom: 'Это подключение уже находится в комнате.',
  errorGameStarted: 'Игра уже началась.',
  errorInvalidPlayerName: 'Введите имя игрока.',
  errorInvalidRoomCode: 'Введите правильный четырёхзначный код комнаты.',
  errorInvalidSession: 'Сохранённая игровая сессия недействительна или устарела.',
  errorNotHost: 'Только ведущий может начать игру.',
  errorPlayerNotFound: 'Игрок не найден в этой комнате.',
  errorRoomFull: 'Комната заполнена: не более 6 игроков.',
  errorRoomNotFound: 'Комнаты с таким кодом не существует.',
  errorGameNotFinished: 'Игра ещё не завершена.',
  errorGameNotFound: 'Игра сейчас не запущена.',
  errorNotActivePlayer: 'Сейчас не ваш ход.',
  errorInvalidPhase: 'Это действие сейчас недоступно.',
  errorNotEnoughPlayers: 'Для начала игры недостаточно игроков.',
  errorActorNotFound: 'Этот игрок не участвует в игре.',
  errorCardNotInHand: 'Этой карты нет у вас в руке.',
  errorCardNotEquipped: 'Этот предмет не надет.',
  errorCardNotEquipment: 'Эта карта не является снаряжением.',
  errorCardNotPlayable: 'Эту карту нельзя сыграть в текущий бой.',
  errorInvalidTarget: 'Для этой карты не выбрана допустимая цель.',
  errorInvalidHelper: 'Этот игрок не может помочь в текущем бою.',
  errorHelpAlreadyAccepted: 'К этому бою уже присоединился помощник.',
  errorHelpNotRequested: 'У вас нет активной просьбы о помощи.',
  errorCombatNotWon: 'Ваша сила должна быть выше силы монстра.',
  errorReactionWindowActive: 'Пока заявлена победа, разрешены только реакции на бой.',
  errorReactionAlreadyConfirmed: 'Вы уже подтвердили, что не вмешиваетесь в этом раунде реакции.',
  errorStaleCombatState: 'Бой изменился. Проверьте силы и заявите победу заново.',
  errorStaleCombatReaction: 'Этот раунд реакции уже устарел. Проверьте обновлённый бой.',
  errorEquipmentSlotOccupied: 'Этот слот снаряжения уже занят.',
  errorNotEnoughFreeHands: 'У вас недостаточно свободных рук.',
  errorClassRequired: 'Для этого предмета нужен другой класс.',
  errorRaceRequired: 'Для этого предмета нужна другая раса.',
  errorInvalidRecipient: 'Выберите допустимого получателя.',
  errorInvalidCardSelection: 'Выберите нужное количество карт.',
  errorInsufficientSaleValue: 'Выбранные предметы не стоят 1 000 золотых.',
  errorHandLimitExceeded: 'Перед завершением хода раздайте милостыню.',
  errorCommandNotAvailable: 'Это действие пока недоступно.',
  errorDeckEmpty: 'В этой колоде не осталось карт.',
  errorDuplicatePlayer: 'Этот игрок уже участвует в игре.',
  errorInsufficientCards: 'В колоде и сбросе недостаточно карт для этого действия.',
  errorPlayerLimit: 'В игре уже максимальное количество игроков.',
  errorUnknown: 'Что-то пошло не так. Попробуйте ещё раз.',
};

const TRANSLATIONS = { en: ENGLISH, ru: RUSSIAN } as const;
const LOCALE_STORAGE_KEY = 'munchkin-lan.locale';

const ERROR_KEYS: Readonly<Record<string, TranslationKey>> = {
  CONNECTION_LOST: 'errorConnectionLost',
  SERVER_UNAVAILABLE: 'errorServerUnavailable',
  ALREADY_IN_ROOM: 'errorAlreadyInRoom',
  GAME_ALREADY_STARTED: 'errorGameStarted',
  INVALID_PLAYER_NAME: 'errorInvalidPlayerName',
  INVALID_ROOM_CODE: 'errorInvalidRoomCode',
  INVALID_SESSION: 'errorInvalidSession',
  NOT_HOST: 'errorNotHost',
  PLAYER_NOT_FOUND: 'errorPlayerNotFound',
  ROOM_FULL: 'errorRoomFull',
  ROOM_NOT_FOUND: 'errorRoomNotFound',
  GAME_NOT_FINISHED: 'errorGameNotFinished',
  GAME_NOT_FOUND: 'errorGameNotFound',
  NOT_ACTIVE_PLAYER: 'errorNotActivePlayer',
  INVALID_PHASE: 'errorInvalidPhase',
  NOT_ENOUGH_PLAYERS: 'errorNotEnoughPlayers',
  ACTOR_NOT_FOUND: 'errorActorNotFound',
  CARD_NOT_IN_HAND: 'errorCardNotInHand',
  CARD_NOT_EQUIPPED: 'errorCardNotEquipped',
  CARD_NOT_EQUIPMENT: 'errorCardNotEquipment',
  CARD_NOT_PLAYABLE: 'errorCardNotPlayable',
  INVALID_TARGET: 'errorInvalidTarget',
  INVALID_HELPER: 'errorInvalidHelper',
  HELP_ALREADY_ACCEPTED: 'errorHelpAlreadyAccepted',
  HELP_NOT_REQUESTED: 'errorHelpNotRequested',
  COMBAT_NOT_WON: 'errorCombatNotWon',
  REACTION_WINDOW_ACTIVE: 'errorReactionWindowActive',
  REACTION_ALREADY_CONFIRMED: 'errorReactionAlreadyConfirmed',
  STALE_COMBAT_STATE: 'errorStaleCombatState',
  STALE_COMBAT_REACTION: 'errorStaleCombatReaction',
  EQUIPMENT_SLOT_OCCUPIED: 'errorEquipmentSlotOccupied',
  NOT_ENOUGH_FREE_HANDS: 'errorNotEnoughFreeHands',
  CLASS_REQUIRED: 'errorClassRequired',
  RACE_REQUIRED: 'errorRaceRequired',
  INVALID_RECIPIENT: 'errorInvalidRecipient',
  INVALID_CARD_SELECTION: 'errorInvalidCardSelection',
  INSUFFICIENT_SALE_VALUE: 'errorInsufficientSaleValue',
  HAND_LIMIT_EXCEEDED: 'errorHandLimitExceeded',
  COMMAND_NOT_AVAILABLE: 'errorCommandNotAvailable',
  DECK_EMPTY: 'errorDeckEmpty',
  DUPLICATE_PLAYER_ID: 'errorDuplicatePlayer',
  INSUFFICIENT_CARDS: 'errorInsufficientCards',
  PLAYER_LIMIT_REACHED: 'errorPlayerLimit',
};

interface CardTranslation {
  readonly name: string;
  readonly description: string;
}

export const RUSSIAN_CARDS: Readonly<Record<string, CardTranslation>> = {
  'dust-bunny-brigade': {
    name: 'Бригада пылевых кроликов',
    description: 'Удивительно организованная угроза из-под дивана.',
  },
  'corridor-crab': {
    name: 'Коридорный краб',
    description: 'Он захватил коридор и отказывается вести переговоры.',
  },
  'whispering-vending-machine': {
    name: 'Шепчущий торговый автомат',
    description: 'Принимает точную сумму и расплывчатые обещания.',
  },
  'bureaucratic-ooze': {
    name: 'Бюрократическая слизь',
    description: 'Для каждой атаки нужны три одинаковые справки.',
  },
  'clockwork-yak': {
    name: 'Заводной як',
    description: 'Громкий, упрямый и слишком туго заведённый.',
  },
  'staircase-centipede': {
    name: 'Лестничная сороконожка',
    description: 'У неё есть туфля для каждой ступеньки и счёт для каждой туфли.',
  },
  'archive-dragon': {
    name: 'Архивный дракон',
    description: 'Копит первые издания, последние предупреждения и всех, кто шепчет.',
  },
  'moonlit-leviathan': {
    name: 'Лунный левиафан',
    description: 'Он не помещается в комнате, но каким-то образом уже внутри.',
  },
  'curse-shortcut-tax': {
    name: 'Проклятие! Налог на короткий путь',
    description: 'Потеряйте один уровень за подозрительно удобный маршрут.',
  },
  'curse-memory-moths': {
    name: 'Проклятие! Моль забвения',
    description: 'Выберите и сбросьте одну карту из руки.',
  },
  'curse-double-backtrack': {
    name: 'Проклятие! Двойной возврат',
    description: 'Потеряйте два уровня, но не опускайтесь ниже первого.',
  },
  'curse-career-fog': {
    name: 'Проклятие! Карьерный туман',
    description: 'Сбросьте свой текущий класс.',
  },
  'curse-pocket-gravity': {
    name: 'Проклятие! Карманная гравитация',
    description: 'Выберите один надетый предмет: он стал слишком тяжёлым.',
  },
  'curse-unread-map': {
    name: 'Проклятие! Непрочитанная карта',
    description: 'Сбросьте текущую расу, уверенно свернув не туда.',
  },
  'curse-tangled-bootlaces': {
    name: 'Боевое проклятие! Запутавшиеся шнурки',
    description:
      'Во время реакции на победу один участник со стороны приключенцев теряет три силы.',
  },
  'guild-of-echoes': {
    name: 'Гильдия эха',
    description: 'Звучный класс, которому доверяют отвечающие инструменты.',
  },
  'cartographers-circle': {
    name: 'Круг картографов',
    description: 'Класс, считающий каждый неверный поворот ценным полевым исследованием.',
  },
  'lantern-folk': {
    name: 'Народ фонарей',
    description: 'Светлая раса с талантом находить дорогу.',
  },
  mosskin: {
    name: 'Моховики',
    description: 'Терпеливая раса, превращающая паузу в маленькую экосистему.',
  },
  'open-mic-night-invitation': {
    name: 'Приглашение на открытый микрофон',
    description: 'Выберите монстра с руки: он присоединяется к текущему бою.',
  },
  'spatula-of-resolve': {
    name: 'Лопатка решимости',
    description: 'Проверенное на кухне снаряжение с бонусом +2 к боевой силе.',
  },
  'helmet-of-mild-foresight': {
    name: 'Шлем лёгкого предвидения',
    description: 'Вы замечаете опасность примерно на секунду раньше.',
  },
  'boots-of-purposeful-squeaking': {
    name: 'Сапоги уверенного скрипа',
    description: 'Скрытность переоценена, а уверенность даёт +2 к силе.',
  },
  'cardboard-plate-mail': {
    name: 'Картонные латы',
    description: 'Зависящая от погоды защита с бонусом +3 к силе.',
  },
  'two-handed-bookmark': {
    name: 'Двуручная закладка',
    description: 'Отмечает и нужную страницу, и врагов, которых пора победить.',
  },
  'compass-crown': {
    name: 'Корона-компас',
    description: 'Любое направление становится верным, если объявить его достаточно торжественно.',
  },
  'coat-of-many-pockets': {
    name: 'Пальто многих карманов',
    description: 'Большинство карманов — обманки, зато полезные просто превосходны.',
  },
  'deadline-skates': {
    name: 'Дедлайновые коньки',
    description: 'Они едут быстрее лишь тогда, когда маршрут ещё рисуют.',
  },
  'tuning-fork-rapier': {
    name: 'Рапира-камертон',
    description: 'Точная нота с неожиданно острым завершением.',
  },
  'portable-drawbridge': {
    name: 'Переносной подъёмный мост',
    description: 'Тяжёлый, непрактичный и превосходно завершает спор.',
  },
  'bottled-applause': {
    name: 'Аплодисменты в бутылке',
    description: 'Откройте и ненадолго получите +3 к уверенности и боевой силе.',
  },
  'pocket-comet': {
    name: 'Карманная комета',
    description: 'Маленькая, сияющая и дающая временный бонус +5.',
  },
  'emergency-confetti': {
    name: 'Аварийное конфетти',
    description: 'Красочный отвлекающий манёвр с временным бонусом +2.',
  },
  'heroic-snack-break': {
    name: 'Героический перекус',
    description: 'Вовремя съеденное печенье даёт приключенцам четыре силы.',
  },
  'borrowed-thunder': {
    name: 'Гром напрокат',
    description: 'Верните до заката; до тех пор он даёт шесть силы.',
  },
  'ominous-stage-light': {
    name: 'Зловещий свет рампы',
    description: 'Драматичное освещение временно даёт выбранному монстру четыре силы.',
  },
  'strategic-banana-peel': {
    name: 'Стратегическая банановая кожура',
    description: 'Один монстр теряет три силы, пытаясь удержаться на ногах.',
  },
  'inflatable-shoulder-pads': {
    name: 'Надувные наплечники',
    description: 'Монстр выглядит на четыре пункта внушительнее.',
  },
  'dramatic-entrance-music': {
    name: 'Драматическая музыка для выхода',
    description: 'Необязательная фанфара добавляет монстру две силы.',
  },
  'executive-monster-promotion': {
    name: 'Служебное повышение монстра',
    description: 'Один монстр получает пять силы и две Сокровищницы.',
  },
  'mandatory-monster-nap': {
    name: 'Обязательный сон для монстра',
    description: 'Один монстр теряет пять силы и одно Сокровище в обычных пределах.',
  },
  'bureaucratic-carbon-copy': {
    name: 'Бюрократическая копирка',
    description: 'Создайте независимый снимок одного монстра в бою.',
  },
};

@Injectable({ providedIn: 'root' })
export class LocalizationService {
  private readonly currentLocale = signal<AppLocale>(
    window.localStorage.getItem(LOCALE_STORAGE_KEY) === 'en' ? 'en' : 'ru',
  );

  readonly locale = this.currentLocale.asReadonly();

  constructor() {
    this.applyDocumentLanguage(this.currentLocale());
  }

  translate(key: TranslationKey): string {
    return TRANSLATIONS[this.currentLocale()][key];
  }

  setLocale(locale: AppLocale): void {
    this.currentLocale.set(locale);
    window.localStorage.setItem(LOCALE_STORAGE_KEY, locale);
    this.applyDocumentLanguage(locale);
  }

  errorMessage(error: UserFacingError): string {
    const key = ERROR_KEYS[error.code];
    if (key !== undefined) return this.translate(key);
    return this.currentLocale() === 'en' && error.message.length > 0
      ? error.message
      : this.translate('errorUnknown');
  }

  cardName(card: GameCardView): string {
    return this.currentLocale() === 'ru'
      ? (RUSSIAN_CARDS[card.definitionId]?.name ?? card.name)
      : card.name;
  }

  cardDescription(card: GameCardView): string {
    return this.currentLocale() === 'ru'
      ? (RUSSIAN_CARDS[card.definitionId]?.description ?? card.description)
      : card.description;
  }

  definitionName(definitionId: string): string {
    const translated = RUSSIAN_CARDS[definitionId]?.name;
    if (this.currentLocale() === 'ru' && translated !== undefined) return translated;
    return definitionId
      .split('-')
      .filter(Boolean)
      .map((part) => `${part.at(0)?.toUpperCase() ?? ''}${part.slice(1)}`)
      .join(' ');
  }

  cardsCount(count: number): string {
    if (this.currentLocale() === 'en') return `${count} ${count === 1 ? 'card' : 'cards'}`;
    const lastTwo = count % 100;
    const last = count % 10;
    const noun =
      lastTwo >= 11 && lastTwo <= 14
        ? 'карт'
        : last === 1
          ? 'карта'
          : last >= 2 && last <= 4
            ? 'карты'
            : 'карт';
    return `${count} ${noun}`;
  }

  private applyDocumentLanguage(locale: AppLocale): void {
    document.documentElement.lang = locale;
    document.title = locale === 'ru' ? 'Манчкин по локальной сети' : 'Munchkin LAN';
  }
}
